# Project 4: Predicting good/bad loans among high-risk loans using Lending Club data

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
loans = pd.read_csv('loans.zip')
loans.head()

C:\Users\oroni\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (124,125,126,129,130,131,134,140,141,142) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_ind
0,0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,...,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,...,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,...,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1
3,3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,...,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1
4,4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,...,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1

## Data dictionary

In [54]:
browse_notes = pd.read_excel('LCDataDictionary.xlsx', sheet_name=0)
browse_notes

,LoanStatNew,Description
0,acc_now_delinq,The number of accounts on which the borrower i...
1,acc_open_past_24mths,Number of trades opened in past 24 months.
2,addr_state,The state provided by the borrower in the loan...
3,all_util,Balance to credit limit on all trades
4,annual_inc,The self-reported annual income provided by th...
5,annual_inc_joint,The combined self-reported annual income provi...
6,application_type,Indicates whether the loan is an individual ap...
7,avg_cur_bal,Average current balance of all accounts
8,bc_open_to_buy,Total open to buy on revolving bankcards.
9,bc_util,Ratio of total current balance to high credit/...
10,chargeoff_within_12_mths,Number of charge-offs within 12 months
11,collection_recovery_fee,post charge off collection fee
12,collections_12_mths_ex_med,Number of collections in 12 months excluding m...
13,delinq_2yrs,The number of 30+ days past-due incidences of ...
14,delinq_amnt,The past-due amount owed for the accounts on w...
15,desc,Loan description provided by the borrower
16,dti,A ratio calculated using the borrowerâ€™s total ...
17,dti_joint,A ratio calculated using the co-borrowers' tot...
18,earliest_cr_line,The month the borrower's earliest reported cre...
19,emp_length,Employment length in years. Possible values ar...
20,emp_title,The job title supplied by the Borrower when ap...
21,fico_range_high,The upper boundary range the borrowerâ€™s FICO a...
22,fico_range_low,The lower boundary range the borrowerâ€™s FICO a...
23,funded_amnt,The total amount committed to that loan at tha...
24,funded_amnt_inv,The total amount committed by investors for th...
25,grade,LC assigned loan grade
26,home_ownership,The home ownership status provided by the borr...
27,id,A unique LC assigned ID for the loan listing.
28,il_util,Ratio of total current balance to high credit/...
29,initial_list_status,The initial listing status of the loan. Possib...
...,...,...
123,sec_app_open_act_il,Number of currently active installment trades...
124,sec_app_num_rev_accts,Number of revolving accounts at time of appli...
125,sec_app_chargeoff_within_12_mths,Number of charge-offs within last 12 months a...
126,sec_app_collections_12_mths_ex_med,Number of collections within last 12 months e...
127,sec_app_mths_since_last_major_derog,Months since most recent 90-day or worse rati...
128,hardship_flag,Flags whether or not the borrower is on a hard...
129,hardship_type,Describes the hardship plan offering
130,hardship_reason,Describes the reason the hardship plan was off...
131,hardship_status,"Describes if the hardship plan is active, pend..."
132,deferral_term,Amount of months that the borrower is expected...
133,hardship_amount,The interest payment that the borrower has com...
134,hardship_start_date,The start date of the hardship plan period
135,hardship_end_date,The end date of the hardship plan period
136,payment_plan_start_date,The day the first hardship plan payment is due...
137,hardship_length,The number of months the borrower will make sm...
138,hardship_dpd,Account days past due as of the hardship plan ...
139,hardship_loan_status,Loan Status as of the hardship plan start date
140,orig_projected_additional_accrued_interest,The original projected additional interest amo...
141,hardship_payoff_balance_amount,The payoff balance amount as of the hardship p...
142,hardship_last_payment_amount,The last payment amount as of the hardship pla...
143,disbursement_method,The method by which the borrower receives thei...
144,debt_settlement_flag,"Flags whether or not the borrower, who has cha..."
145,debt_settlement_flag_date,The most recent date that the Debt_Settlement_...
146,settlement_status,The status of the borrowerâ€™s settlement plan. ...
147,settlement_date,The date that the borrower agrees to the settl...
148,settlement_amount,The loan amount that the borrower has agreed t...
149,settlement_percentage,The settlement amount as a percentage of the p...
150,settlement_term,The number of months that the borrower will be...
151,NaN,NaN
152,NaN,* Employer Title replaces Employer Name for al...

## Basic EDA

### This uses all data.

In [63]:
# proportion of missing values 
null_prop = loans.isnull().mean()
print(null_prop[null_prop!=0].sort_values(ascending=False))

id                                            1.000000
member_id                                     1.000000
url                                           1.000000
desc                                          1.000000
orig_projected_additional_accrued_interest    0.999530
payment_plan_start_date                       0.999455
hardship_status                               0.999455
deferral_term                                 0.999455
hardship_amount                               0.999455
hardship_start_date                           0.999455
hardship_end_date                             0.999455
hardship_loan_status                          0.999455
hardship_length                               0.999455
hardship_dpd                                  0.999455
hardship_type                                 0.999455
hardship_payoff_balance_amount                0.999455
hardship_last_payment_amount                  0.999455
hardship_reason                               0.999455
settlement_percentage                         0.999241
settlement_term                               0.999241
settlement_date                               0.999241
debt_settlement_flag_date                     0.999241
settlement_status                             0.999241
settlement_amount                             0.999241
sec_app_mths_since_last_major_derog           0.954816
mths_since_last_record                        0.872822
verification_status_joint                     0.870748
sec_app_revol_util                            0.863121
sec_app_open_acc                              0.860704
sec_app_mort_acc                              0.860704
                                                ...
revol_bal_joint                               0.860704
sec_app_open_act_il                           0.860704
sec_app_num_rev_accts                         0.860704
sec_app_chargeoff_within_12_mths              0.860704
annual_inc_joint                              0.860704
dti_joint                                     0.860704
sec_app_earliest_cr_line                      0.860704
mths_since_recent_bc_dlq                      0.801895
mths_since_last_major_derog                   0.768128
mths_since_recent_revol_delinq                0.711878
mths_since_last_delinq                        0.558620
il_util                                       0.163201
mths_since_recent_inq                         0.123788
emp_title                                     0.110368
next_pymnt_d                                  0.095271
emp_length                                    0.084781
mo_sin_old_il_acct                            0.037174
mths_since_rcnt_il                            0.037174
num_tl_120dpd_2m                              0.025046
bc_util                                       0.013737
percent_bc_gt_75                              0.013319
bc_open_to_buy                                0.013303
mths_since_recent_bc                          0.012515
dti                                           0.002286
last_pymnt_d                                  0.001290
revol_util                                    0.001195
all_util                                      0.000260
avg_cur_bal                                   0.000081
last_credit_pull_d                            0.000012
pct_tl_nvr_dlq                                0.000004
Length: 62, dtype: float64

In [65]:
# datatypes
print(loans.dtypes)

Unnamed: 0                                      int64
id                                            float64
member_id                                     float64
loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                      float64
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
url                                           float64
desc                                          float64
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                   float64
earliest_cr_line                               object
inq_last_6mths                                float64
mths_since_last_delinq                        float64
                                               ...
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
disbursement_method                            object
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
loan_status_ind                                 int64
Length: 147, dtype: object

In [66]:
# shape 
loans.shape

(495242, 147)

In [68]:
# summary stats 
loans.describe()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,...,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term,loan_status_ind
count,495242.000000,0.0,0.0,495242.000000,495242.000000,495242.000000,495242.000000,495242.000000,4.952420e+05,0.0,...,270.000000,270.0,270.000000,233.000000,270.000000,270.000000,376.000000,376.000000,376.000000,495242.000000
mean,247620.500000,NaN,NaN,16025.020394,16025.020394,16021.668722,12.729272,466.614617,8.009399e+04,NaN,...,198.084370,3.0,11.977778,591.397597,15740.816852,205.039593,7050.864043,55.058670,18.382979,0.970150
std,142964.195344,NaN,NaN,10138.075023,10138.075023,10137.900881,5.150130,286.910450,8.887161e+04,NaN,...,151.944225,0.0,9.434940,465.875246,9582.705213,211.514958,5035.647613,9.598626,6.157240,0.170174
min,0.000000,NaN,NaN,1000.000000,1000.000000,725.000000,5.310000,29.760000,0.000000e+00,NaN,...,5.950000,3.0,0.000000,17.850000,424.110000,0.070000,413.930000,30.480000,1.000000,0.000000
25%,123810.250000,NaN,NaN,8000.000000,8000.000000,8000.000000,8.460000,254.560000,4.600000e+04,NaN,...,88.622500,3.0,2.000000,258.720000,8202.280000,32.870000,3316.412500,45.000000,18.000000,1.000000
50%,247620.500000,NaN,NaN,14000.000000,14000.000000,14000.000000,11.800000,386.820000,6.600000e+04,NaN,...,159.425000,3.0,11.000000,424.260000,13247.860000,149.855000,5450.570000,60.000000,18.000000,1.000000
75%,371430.750000,NaN,NaN,22000.000000,22000.000000,22000.000000,16.010000,629.040000,9.600000e+04,NaN,...,274.552500,3.0,20.000000,819.900000,22529.437500,314.047500,9623.287500,65.000000,24.000000,1.000000
max,495241.000000,NaN,NaN,40000.000000,40000.000000,40000.000000,30.990000,1670.150000,9.930475e+06,NaN,...,845.220000,3.0,29.000000,2535.660000,40149.350000,1072.990000,28503.000000,80.000000,24.000000,1.000000

In [69]:
# unique values per feature 
loans.nunique()

Unnamed: 0                                    495242
id                                                 0
member_id                                          0
loan_amnt                                       1559
funded_amnt                                     1559
funded_amnt_inv                                 1571
term                                               2
int_rate                                         110
installment                                    35297
grade                                              7
sub_grade                                         35
emp_title                                     129449
emp_length                                        11
home_ownership                                     4
annual_inc                                     30071
verification_status                                3
issue_d                                           12
loan_status                                        7
pymnt_plan                                         2
url                                                0
desc                                               0
purpose                                           13
title                                             12
zip_code                                         897
addr_state                                        50
dti                                             9464
delinq_2yrs                                       26
earliest_cr_line                                 684
inq_last_6mths                                     6
mths_since_last_delinq                           158
                                               ...
sec_app_revol_util                              1164
sec_app_open_act_il                               37
sec_app_num_rev_accts                             81
sec_app_chargeoff_within_12_mths                  21
sec_app_collections_12_mths_ex_med                17
sec_app_mths_since_last_major_derog              136
hardship_flag                                      2
hardship_type                                      1
hardship_reason                                    8
hardship_status                                    3
deferral_term                                      1
hardship_amount                                  269
hardship_start_date                                8
hardship_end_date                                  8
payment_plan_start_date                            8
hardship_length                                    1
hardship_dpd                                      30
hardship_loan_status                               5
orig_projected_additional_accrued_interest       233
hardship_payoff_balance_amount                   270
hardship_last_payment_amount                     263
disbursement_method                                2
debt_settlement_flag                               2
debt_settlement_flag_date                         10
settlement_status                                  3
settlement_date                                   10
settlement_amount                                375
settlement_percentage                             33
settlement_term                                   16
loan_status_ind                                    2
Length: 147, dtype: int64

In [76]:
print('mean int rate by grade: ')
print(loans.groupby('grade').int_rate.mean())
print('standard deviation of int rate by grade: ')
print(loans.groupby('grade').int_rate.std())

mean int rate by grade:
grade
A     7.081353
B    10.918785
C    14.711079
D    19.489090
E    25.175089
F    29.482948
G    30.816751
Name: int_rate, dtype: float64
standard deviation of int rate by grade:
grade
A    0.947378
B    0.975104
C    1.260743
D    1.516637
E    1.460112
F    1.000191
G    0.052152
Name: int_rate, dtype: float64

### Only data with grade in ['E', 'F', 'G']

In [78]:
risky_loans = loans[loans.grade.isin(['E', 'F', 'G'])]

In [80]:
# shape 
risky_loans.shape

(22804, 147)

In [81]:
# proportion of missing values 
null_prop_risky = risky_loans.isnull().mean()
print(null_prop_risky[null_prop_risky!=0].sort_values(ascending=False))

id                                            1.000000
member_id                                     1.000000
url                                           1.000000
desc                                          1.000000
orig_projected_additional_accrued_interest    0.998948
payment_plan_start_date                       0.998772
hardship_status                               0.998772
deferral_term                                 0.998772
hardship_amount                               0.998772
hardship_start_date                           0.998772
hardship_end_date                             0.998772
hardship_loan_status                          0.998772
hardship_length                               0.998772
hardship_dpd                                  0.998772
hardship_type                                 0.998772
hardship_payoff_balance_amount                0.998772
hardship_last_payment_amount                  0.998772
hardship_reason                               0.998772
settlement_percentage                         0.997807
settlement_term                               0.997807
settlement_amount                             0.997807
settlement_date                               0.997807
settlement_status                             0.997807
debt_settlement_flag_date                     0.997807
sec_app_mths_since_last_major_derog           0.911989
mths_since_last_record                        0.871777
sec_app_revol_util                            0.797711
verification_status_joint                     0.795036
sec_app_collections_12_mths_ex_med            0.791221
annual_inc_joint                              0.791221
                                                ...
revol_bal_joint                               0.791221
sec_app_inq_last_6mths                        0.791221
sec_app_earliest_cr_line                      0.791221
sec_app_open_act_il                           0.791221
sec_app_num_rev_accts                         0.791221
sec_app_mort_acc                              0.791221
sec_app_open_acc                              0.791221
sec_app_chargeoff_within_12_mths              0.791221
mths_since_recent_bc_dlq                      0.764340
mths_since_last_major_derog                   0.720005
mths_since_recent_revol_delinq                0.665629
mths_since_last_delinq                        0.501754
next_pymnt_d                                  0.142080
il_util                                       0.129670
emp_title                                     0.120286
emp_length                                    0.095553
mths_since_recent_inq                         0.086695
num_tl_120dpd_2m                              0.050210
mo_sin_old_il_acct                            0.040256
mths_since_rcnt_il                            0.040256
bc_util                                       0.023899
percent_bc_gt_75                              0.023505
bc_open_to_buy                                0.023417
mths_since_recent_bc                          0.022540
last_pymnt_d                                  0.004955
dti                                           0.004210
revol_util                                    0.002017
all_util                                      0.000395
avg_cur_bal                                   0.000219
pct_tl_nvr_dlq                                0.000044
Length: 61, dtype: float64

In [84]:
# summary stats 
risky_loans.describe()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,...,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term,loan_status_ind
count,22804.000000,0.0,0.0,22804.000000,22804.000000,22804.000000,22804.000000,22804.000000,2.280400e+04,0.0,...,28.000000,28.0,28.000000,24.000000,28.000000,28.000000,50.000000,50.000000,50.0000,22804.000000
mean,236339.136818,NaN,NaN,15954.279951,15954.279951,15953.663831,25.940876,525.699668,7.264588e+04,NaN,...,414.010357,3.0,12.857143,1270.443750,19023.961786,177.902500,8056.487000,53.000200,20.2400,0.916506
std,142227.980605,NaN,NaN,9354.111004,9354.111004,9353.796331,2.201294,302.148206,9.128517e+04,NaN,...,247.904281,0.0,9.046032,770.452135,10462.236878,278.721125,5869.457148,9.422554,5.8189,0.276634
min,22.000000,NaN,NaN,1000.000000,1000.000000,1000.000000,6.000000,38.660000,0.000000e+00,NaN,...,57.850000,3.0,0.000000,173.550000,3522.950000,0.100000,887.270000,40.000000,1.0000,0.000000
25%,113937.000000,NaN,NaN,10000.000000,10000.000000,10000.000000,24.370000,306.970000,4.000000e+04,NaN,...,238.467500,3.0,5.000000,715.402500,12340.507500,18.317500,4416.702500,45.000000,18.0000,1.000000
50%,229413.500000,NaN,NaN,15000.000000,15000.000000,15000.000000,25.810000,481.005000,6.000000e+04,NaN,...,388.960000,3.0,13.000000,1166.880000,18136.675000,60.610000,6509.975000,45.000000,24.0000,1.000000
75%,357111.750000,NaN,NaN,23200.000000,23200.000000,23200.000000,27.270000,738.780000,8.600000e+04,NaN,...,578.060000,3.0,21.250000,1781.857500,28266.095000,185.347500,10647.000000,64.985000,24.0000,1.000000
max,495058.000000,NaN,NaN,40000.000000,40000.000000,40000.000000,30.990000,1670.150000,8.500000e+06,NaN,...,845.220000,3.0,28.000000,2535.660000,38079.560000,1072.990000,28503.000000,70.030000,24.0000,1.000000

In [85]:
# unique values per feature 
risky_loans.nunique()

Unnamed: 0                                    22804
id                                                0
member_id                                         0
loan_amnt                                      1209
funded_amnt                                    1209
funded_amnt_inv                                1221
term                                              2
int_rate                                         26
installment                                    5313
grade                                             3
sub_grade                                        15
emp_title                                     10694
emp_length                                       11
home_ownership                                    4
annual_inc                                     3244
verification_status                               3
issue_d                                          12
loan_status                                       7
pymnt_plan                                        2
url                                               0
desc                                              0
purpose                                          13
title                                            12
zip_code                                        851
addr_state                                       50
dti                                            5053
delinq_2yrs                                      17
earliest_cr_line                                556
inq_last_6mths                                    6
mths_since_last_delinq                          114
                                              ...
sec_app_revol_util                              953
sec_app_open_act_il                              30
sec_app_num_rev_accts                            62
sec_app_chargeoff_within_12_mths                 12
sec_app_collections_12_mths_ex_med                9
sec_app_mths_since_last_major_derog              88
hardship_flag                                     2
hardship_type                                     1
hardship_reason                                   6
hardship_status                                   3
deferral_term                                     1
hardship_amount                                  28
hardship_start_date                               7
hardship_end_date                                 6
payment_plan_start_date                           6
hardship_length                                   1
hardship_dpd                                     14
hardship_loan_status                              4
orig_projected_additional_accrued_interest       24
hardship_payoff_balance_amount                   28
hardship_last_payment_amount                     28
disbursement_method                               2
debt_settlement_flag                              2
debt_settlement_flag_date                         8
settlement_status                                 3
settlement_date                                   9
settlement_amount                                50
settlement_percentage                            11
settlement_term                                   7
loan_status_ind                                   2
Length: 147, dtype: int64

## Handling missing values

The features id, member_id, url and desc are completely empty - remove them.

In [86]:
risky_loans = risky_loans.drop(['id', 'member_id', 'url', 'desc'], axis=1, errors='ignore')

For categorical features (emp_title, verification_status_joint), the missing values should be filled with an empty string - put into list fill_empty.

For some of the numerical features (eg. mths_since_last_record), the missing values should be filled using the maximum value of the respective columns - put into list fill_max. 

For the rest of the numerical features (e.g. emp_length), the missing values should be filled using the minimum value of the respective columns - put into list fill_min.

In [88]:
fill_empty = ['emp_title', 
              'verification_status_joint']
fill_max = ['bc_open_to_buy', 
            'mo_sin_old_il_acct', 
            'mths_since_last_delinq',
            'mths_since_last_major_derog', 
            'mths_since_last_record',
            'mths_since_rcnt_il', 
            'mths_since_recent_bc', 
            'mths_since_recent_bc_dlq',
            'mths_since_recent_inq', 
            'mths_since_recent_revol_delinq',
            'pct_tl_nvr_dlq',
            'sec_app_mths_since_last_major_derog']
fill_min = np.setdiff1d(risky_loans.columns.values, np.append(fill_empty, fill_max))

In [92]:
risky_loans[fill_empty] = risky_loans[fill_empty].fillna('')
risky_loans[fill_max] = risky_loans[fill_max].fillna(risky_loans[fill_max].max())
risky_loans[fill_min] = risky_loans[fill_min].fillna(risky_loans[fill_min].min())

## Multicollinearity

Calculate pairwise Pearson correlations for numerical features and remove features with very high correlation coefficients.

In [94]:
from itertools import combinations
from scipy.stats import pearsonr

num_feat = risky_loans.select_dtypes('number').columns.values
comb_num_feat = np.array(list(combinations(num_feat, 2)))
corr_num_feat = np.array([])
for comb in comb_num_feat:
    corr = pearsonr(risky_loans[comb[0]], risky_loans[comb[1]])[0]
    corr_num_feat = np.append(corr_num_feat, corr)

C:\Users\oroni\Anaconda3\lib\site-packages\scipy\stats\stats.py:3038: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den

In [96]:
high_corr_num = comb_num_feat[np.abs(corr_num_feat) >= 0.9]
high_corr_num

C:\Users\oroni\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater_equal
  """Entry point for launching an IPython kernel.

array([['loan_amnt', 'funded_amnt'],
       ['loan_amnt', 'funded_amnt_inv'],
       ['loan_amnt', 'installment'],
       ['funded_amnt', 'funded_amnt_inv'],
       ['funded_amnt', 'installment'],
       ['funded_amnt_inv', 'installment'],
       ['open_acc', 'num_sats'],
       ['pub_rec', 'pub_rec_bankruptcies'],
       ['revol_bal', 'total_rev_hi_lim'],
       ['out_prncp', 'out_prncp_inv'],
       ['total_pymnt', 'total_pymnt_inv'],
       ['total_pymnt', 'total_rec_prncp'],
       ['total_pymnt_inv', 'total_rec_prncp'],
       ['total_rec_prncp', 'last_pymnt_amnt'],
       ['recoveries', 'collection_recovery_fee'],
       ['acc_now_delinq', 'num_tl_30dpd'],
       ['tot_cur_bal', 'tot_hi_cred_lim'],
       ['total_bal_il', 'total_bal_ex_mort'],
       ['total_bal_il', 'total_il_high_credit_limit'],
       ['num_actv_rev_tl', 'num_rev_tl_bal_gt_0'],
       ['total_bal_ex_mort', 'total_il_high_credit_limit'],
       ['sec_app_open_acc', 'sec_app_num_rev_accts'],
       ['hardship_amount', 'orig_projected_additional_accrued_interest'],
       ['hardship_amount', 'hardship_payoff_balance_amount'],
       ['orig_projected_additional_accrued_interest',
        'hardship_payoff_balance_amount']], dtype='<U42')

In [97]:
# Second feature (chosen arbitrarily) removed 
risky_loans = risky_loans.drop(np.unique(high_corr_num[:, 1]), axis=1, errors='ignore')

In [98]:
risky_loans.shape

(22804, 124)

Calculate pairwise Cramer's V correlation for categorical features and remove features with high correlation coefficients.  Note that Pearson's correlation is not applicable to categorical features and shouldn't be used.

In [100]:
from scipy.stats import chi2_contingency

cat_feat = risky_loans.select_dtypes('object').columns.values
comb_cat_feat = np.array(list(combinations(cat_feat, 2)))
corr_cat_feat = np.array([])
for comb in comb_cat_feat:
    table = pd.pivot_table(risky_loans, values='loan_amnt', index=comb[0], columns=comb[1], aggfunc='count').fillna(0)
    corr = np.sqrt(chi2_contingency(table)[0] / (table.values.sum() * (np.min(table.shape) - 1) ) )
    corr_cat_feat = np.append(corr_cat_feat, corr)

C:\Users\oroni\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide

In [101]:
high_corr_cat = comb_cat_feat[corr_cat_feat >= 0.9]
high_corr_cat

C:\Users\oroni\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater_equal
  """Entry point for launching an IPython kernel.

array([['grade', 'sub_grade'],
       ['emp_title', 'hardship_reason'],
       ['emp_title', 'hardship_status'],
       ['emp_title', 'hardship_start_date'],
       ['emp_title', 'hardship_end_date'],
       ['emp_title', 'payment_plan_start_date'],
       ['emp_title', 'hardship_loan_status'],
       ['emp_title', 'debt_settlement_flag_date'],
       ['emp_title', 'settlement_status'],
       ['emp_title', 'settlement_date'],
       ['pymnt_plan', 'hardship_flag'],
       ['pymnt_plan', 'hardship_status'],
       ['pymnt_plan', 'hardship_end_date'],
       ['purpose', 'title'],
       ['zip_code', 'addr_state'],
       ['zip_code', 'hardship_reason'],
       ['zip_code', 'hardship_status'],
       ['zip_code', 'hardship_start_date'],
       ['zip_code', 'hardship_end_date'],
       ['zip_code', 'payment_plan_start_date'],
       ['zip_code', 'hardship_loan_status'],
       ['zip_code', 'debt_settlement_flag_date'],
       ['zip_code', 'settlement_status'],
       ['zip_code', 'settlement_date'],
       ['earliest_cr_line', 'hardship_reason'],
       ['earliest_cr_line', 'hardship_status'],
       ['earliest_cr_line', 'hardship_start_date'],
       ['earliest_cr_line', 'hardship_end_date'],
       ['earliest_cr_line', 'payment_plan_start_date'],
       ['earliest_cr_line', 'hardship_loan_status'],
       ['earliest_cr_line', 'debt_settlement_flag_date'],
       ['earliest_cr_line', 'settlement_status'],
       ['earliest_cr_line', 'settlement_date'],
       ['application_type', 'verification_status_joint'],
       ['sec_app_earliest_cr_line', 'hardship_reason'],
       ['sec_app_earliest_cr_line', 'hardship_status'],
       ['sec_app_earliest_cr_line', 'hardship_start_date'],
       ['sec_app_earliest_cr_line', 'hardship_end_date'],
       ['sec_app_earliest_cr_line', 'payment_plan_start_date'],
       ['sec_app_earliest_cr_line', 'hardship_loan_status'],
       ['sec_app_earliest_cr_line', 'debt_settlement_flag_date'],
       ['sec_app_earliest_cr_line', 'settlement_status'],
       ['sec_app_earliest_cr_line', 'settlement_date'],
       ['hardship_flag', 'hardship_status'],
       ['hardship_flag', 'hardship_end_date'],
       ['hardship_start_date', 'debt_settlement_flag'],
       ['hardship_end_date', 'debt_settlement_flag'],
       ['payment_plan_start_date', 'debt_settlement_flag']], dtype='<U25')

In [102]:
risky_loans = risky_loans.drop(np.unique(high_corr_cat[:, 1]), axis=1, errors='ignore')

In [103]:
risky_loans.shape

(22804, 109)

In [ ]:
# left with 109 features from original 147

## Target variable

The target feature for this dataset is an indicator if the loan is good (1) or bad (0). 

The description for each loan_status is provided as follows:

Current: Loan is up to date on all outstanding payments.

In Grace Period: Loan is past due but within the 15-day grace period.

Late (16-30): Loan has not been current for 16 to 30 days.

Late (31-120): Loan has not been current for 31 to 120 days.

Fully paid: Loan has been fully repaid, either at the expiration of the 3- or 5-year year term or as a result of a prepayment.

Default: Loan has not been current for an extended period of time.

Charged Off: Loan for which there is no longer a reasonable expectation of further payments.

In [104]:
risky_loans['loan_status'].value_counts()

Current               18332
Fully Paid             2313
Charged Off             927
Late (31-120 days)      847
In Grace Period         255
Late (16-30 days)       129
Default                   1
Name: loan_status, dtype: int64

Decide to label 'Current', 'Fully Paid' and 'In Grace Period' as good loans

In [105]:
y = risky_loans['loan_status'].copy()
y = y.isin(['Current', 'Fully Paid', 'In Grace Period']).astype('int')
y.value_counts()

1    20900
0     1904
Name: loan_status, dtype: int64